"use strict";
/* Goals live in their area. Existing single-person goals remain compatible. */
var areaGoalForm=null,areaGoalEdit=null;
function goalPeople(g){return Array.isArray(g.personIds)?g.personIds.filter(Boolean):(g.personId?[g.personId]:[]);}
function goalFrequency(g){if(!g.cadence)return 'One time';if(g.cadence==='annual')return 'Yearly';if(g.cadence==='custom')return 'Every '+(g.days||2)+' days';return FREQS[g.cadence]?FREQS[g.cadence].label:g.cadence;}
function goalFormHTML(area,g){
 var key=g?g.id:'new',friends=S.people.filter(function(p){return p.area===area;}),chosen=g?goalPeople(g):[];
 var frequencies=[['','One time'],['daily','Daily'],['twicewk','2x a week'],['weekly','Weekly'],['biweekly','Every 2 weeks'],['monthly','Monthly'],['quarterly','Quarterly'],['yearly','Yearly'],['custom','Custom days']];
 return '<div class="area-goal-form" data-goalform="'+esc(key)+'"><label>Title<input data-goalfield="title" value="'+esc(g?g.text:'')+'" placeholder="What do you want to tend to?"></label><label>Description<textarea data-goalfield="details" placeholder="Details (optional)">'+esc(g?(g.details||''):'')+'</textarea></label><div class="area-goal-fields"><label>Frequency<select data-goalfield="cadence">'+frequencies.map(function(o){return '<option value="'+o[0]+'"'+((g&&g.cadence||'')===o[0]?' selected':'')+'>'+o[1]+'</option>';}).join('')+'</select></label><label>Time<select data-goalfield="tod">'+Object.keys(TODS).map(function(t){return '<option value="'+t+'"'+((g&&g.tod||'anytime')===t?' selected':'')+'>'+esc(TODS[t])+'</option>';}).join('')+'</select></label><label data-schedule-day'+(g&&scheduleHasWeekday(g.cadence)?'':' hidden')+'>Day of week<select data-goalfield="scheduleDow">'+scheduleDayOptions(g&&g.scheduleDow)+'</select></label><label>Custom interval (days)<input type="number" min="1" max="365" data-goalfield="days" value="'+(g&&g.days||2)+'"></label></div>'+
 (friends.length?'<fieldset class="area-goal-people"><legend>'+ (area==='friendships'?'Friends':'People') +'</legend>'+friends.map(function(p){return '<label><input type="checkbox" data-goalperson="'+esc(p.id)+'"'+(chosen.indexOf(p.id)!==-1?' checked':'')+'><span>'+personAvatar(p,22)+esc(p.name)+'</span></label>';}).join('')+'</fieldset>':'')+
 '<div class="area-goal-actions"><button type="button" class="btn mini" data-areagoalsave="'+esc(key)+'">Save</button><button type="button" class="btn ghost mini" data-areagoalcancel="'+esc(key)+'">Cancel</button>'+(g?'<button type="button" class="btn ghost mini area-goal-delete" data-areagoaldelete="'+esc(key)+'">Delete</button>':'')+'</div></div>';
}
function areaGoalsHTML(id){
 var goals=areaGoals(id),out='<div class="card area-goals-card" style="margin-bottom:14px"><div class="area-goals-heading"><div class="subhead">Goals</div>'+(!areaGoalForm||areaGoalForm!==id?'<button type="button" class="btn mini" data-areagoaladd="'+esc(id)+'">+ Add goal</button>':'')+'</div>';
 if(areaGoalForm===id)out+=goalFormHTML(id,null);
 if(!goals.length&&areaGoalForm!==id)out+='<div class="empty">No goals yet. Add one here.</div>';
 goals.forEach(function(g){
  if(areaGoalEdit===g.id){out+=goalFormHTML(id,g);return;}
  var last=lastGoalEvent(g),people=goalPeople(g);
  out+='<div class="area-goal-row" id="goal-'+esc(g.id)+'"><div class="area-goal-copy"><div class="area-goal-titleline"><strong>'+esc(g.text)+'</strong>'+people.map(function(pid){var person=S.people.find(function(p){return p.id===pid;});return person?'<button type="button" class="prayer-person area-goal-person" data-openperson="'+esc(pid)+'" aria-label="Open '+esc(person.name)+' profile">'+personAvatar(person,24)+esc(person.name.trim().split(/\s+/)[0])+'</button>':'';}).join('')+'</div>'+(g.details?'<p>'+esc(g.details)+'</p>':'')+'<div class="area-goal-meta">'+esc(goalFrequency(g))+(scheduleDayLabel(g)?' · '+esc(scheduleDayLabel(g)):'')+(g.tod&&g.tod!=='anytime'?' · '+esc(TODS[g.tod]||g.tod):'')+(last?' · Last completed '+new Date(last.ts).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'')+'</div></div><div class="area-goal-row-actions">'+(g.cadence?'<button type="button" class="iconbtn" data-areagoalchart="'+esc(g.id)+'" title="View goal history" aria-label="View '+esc(g.text)+' history"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 3v17h17 M8 16v-5 M13 16V6 M18 16V9"/></svg></button>':'')+'<button type="button" class="iconbtn" data-areagoaledit="'+esc(g.id)+'" title="Edit goal" aria-label="Edit '+esc(g.text)+'">✎</button><button type="button" class="btn mini" data-goaldone="'+esc(g.id)+'">Done</button></div></div>';
 });
 return out+'</div>';
}
function areaHistoryRow(e){
 var ids=Array.isArray(e.personIds)&&e.personIds.length?e.personIds:(e.personId?[e.personId]:[]);
 return '<div class="entry"><div class="entry-main"><div class="entry-head"><span class="entry-date">'+new Date(e.ts).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})+'</span><span class="badge">'+(e.goalCompleted?'Goal completed':esc(typeLabel(e)))+'</span>'+ids.map(function(pid){return '<span class="gr-person">'+esc(personName(pid))+'</span>';}).join('')+'</div>'+(e.title?'<div class="entry-title">'+esc(e.title)+'</div>':'')+(e.note?'<div class="entry-note">'+esc(e.note)+'</div>':'')+'</div><div class="entry-actions"><button class="iconbtn" data-eedit="'+esc(e.id)+'" title="Edit entry">✎</button><button class="iconbtn" data-edel="'+esc(e.id)+'" title="Delete entry">♲</button></div></div>';
}
function areaHistoryHTML(id){
 var events=S.events.filter(function(e){return e.areaId===id&&(id!=='friendships'||e.personId||(e.personIds&&e.personIds.length));}).sort(function(a,b){return b.ts-a.ts;});
 var out='<div class="card area-history-card"><div class="subhead">History</div>';
 if(!events.length)return out+'<div class="empty">Nothing logged yet.</div></div>';
 out+=events.slice(0,10).map(areaHistoryRow).join('');
 if(events.length>10)out+='<details class="area-history-more"><summary>Show more ('+(events.length-10)+')</summary>'+events.slice(10).map(areaHistoryRow).join('')+'</details>';
 return out+'</div>';
}
function readAreaGoalForm(box){var title=box.querySelector('[data-goalfield="title"]').value.trim(),ids=Array.from(box.querySelectorAll('[data-goalperson]:checked')).map(function(c){return c.getAttribute('data-goalperson');}),cadence=box.querySelector('[data-goalfield="cadence"]').value,day=box.querySelector('[data-goalfield="scheduleDow"]').value;return {text:title,details:box.querySelector('[data-goalfield="details"]').value.trim(),cadence:cadence||null,tod:box.querySelector('[data-goalfield="tod"]').value||'anytime',scheduleDow:scheduleHasWeekday(cadence)&&day!==''?+day:null,days:Math.max(1,+box.querySelector('[data-goalfield="days"]').value||2),personIds:ids,personId:ids[0]||null};}
document.addEventListener('change',function(e){if(!e.target.matches('[data-goalfield="cadence"]'))return;var form=e.target.closest('[data-goalform]'),day=form&&form.querySelector('[data-schedule-day]');if(day)day.hidden=!scheduleHasWeekday(e.target.value);});
function openAreaGoalHistory(g){
 var old=document.getElementById('goalHistoryDialog');if(old)old.remove();
 var events=S.events.filter(function(e){return e.goalId===g.id;}).sort(function(a,b){return a.ts-b.ts;}),freq=g.cadence,unit=freq==='daily'?'day':freq==='yearly'||freq==='annual'?'year':freq==='quarterly'?'quarter':freq==='monthly'?'month':freq==='biweekly'?'fortnight':'week',minimum=unit==='day'?30:unit==='week'?24:unit==='fortnight'?12:unit==='month'?12:unit==='quarter'?8:4;
 function floor(date){var d=new Date(date.getFullYear(),date.getMonth(),date.getDate());if(unit==='week')d.setDate(d.getDate()-(d.getDay()+6)%7);if(unit==='fortnight'){var anchor=Date.UTC(1970,0,5),days=Math.floor((Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())-anchor)/864e5);d.setDate(d.getDate()-((days%14)+14)%14);}if(unit==='month')d=new Date(d.getFullYear(),d.getMonth(),1);if(unit==='quarter')d=new Date(d.getFullYear(),Math.floor(d.getMonth()/3)*3,1);if(unit==='year')d=new Date(d.getFullYear(),0,1);return d;}
 function step(d,n){var x=new Date(d);if(unit==='day'||unit==='week'||unit==='fortnight')x.setDate(x.getDate()+n*(unit==='day'?1:unit==='week'?7:14));else x.setMonth(x.getMonth()+n*(unit==='month'?1:unit==='quarter'?3:12));return x;}
 var end=floor(new Date()),start=step(end,1-minimum);if(events.length&&floor(new Date(events[0].ts))<start)start=floor(new Date(events[0].ts));var bins=[];
 for(var date=new Date(start);date<=end;date=step(date,1)){var next=step(date,1),count=events.filter(function(e){return e.ts>=date.getTime()&&e.ts<next.getTime();}).length;bins.push({label:unit==='quarter'?'Q'+(Math.floor(date.getMonth()/3)+1)+' '+date.getFullYear():unit==='year'?String(date.getFullYear()):date.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}),count:count});}
 var max=Math.max.apply(null,[1].concat(bins.map(function(b){return b.count;}))),dialog=document.createElement('dialog');dialog.id='goalHistoryDialog';dialog.className='rhythm-history-dialog';dialog.innerHTML='<div class="history-heading"><div><span class="history-eyebrow">'+esc(goalFrequency(g))+' goal</span><h2>'+esc(g.text)+'</h2></div><button class="iconbtn" data-goalhistoryclose aria-label="Close history">✕</button></div><div class="history-stat"><strong>'+events.length+'</strong> times completed <span>across '+bins.length+' '+unit+'s</span></div><div class="history-scroll" tabindex="0" aria-label="Goal history chart"><div class="history-bars">'+bins.map(function(b){return '<div class="history-column" aria-label="'+esc(b.label)+': '+b.count+' completions" title="'+esc(b.label)+': '+b.count+' completions"><span class="history-count">'+b.count+'</span><span class="history-track"><span class="history-fill" style="height:'+(b.count?Math.max(4,100*b.count/max):2)+'%;background:'+(b.count?'#1E9C68':'var(--line)')+'"></span></span><span class="history-label">'+esc(b.label)+'</span></div>';}).join('')+'</div></div>';
 dialog.addEventListener('click',function(e){if(e.target.closest('[data-goalhistoryclose]'))dialog.close();});dialog.addEventListener('close',function(){dialog.remove();});document.body.appendChild(dialog);dialog.showModal();dialog.querySelector('.history-scroll').scrollLeft=dialog.querySelector('.history-scroll').scrollWidth;
}
document.addEventListener('click',function(e){var b=e.target.closest('[data-areagoaladd],[data-areagoaledit],[data-areagoalcancel],[data-areagoalsave],[data-areagoaldelete],[data-areagoalchart],.area-goals-card [data-goaldone]');if(!b)return;e.stopPropagation();e.preventDefault();var id=b.getAttribute('data-areagoaladd');if(id){areaGoalForm=id;areaGoalEdit=null;render();return;}id=b.getAttribute('data-areagoaledit');if(id){areaGoalEdit=id;areaGoalForm=null;render();return;}id=b.getAttribute('data-areagoalcancel');if(id){areaGoalForm=null;areaGoalEdit=null;render();return;}id=b.getAttribute('data-areagoalchart');if(id){var chartGoal=S.goals.find(function(g){return g.id===id;});if(chartGoal)openAreaGoalHistory(chartGoal);return;}id=b.getAttribute('data-areagoaldelete');if(id){S.goals=S.goals.filter(function(g){return g.id!==id;});areaGoalEdit=null;save();render();flash('Goal deleted');return;}id=b.getAttribute('data-areagoalsave');if(id){var box=b.closest('[data-goalform]'),fields=readAreaGoalForm(box);if(!fields.text){flash('Add a goal title');box.querySelector('[data-goalfield="title"]').focus();return;}if(currentArea==='friendships'&&!fields.personIds.length){flash('Choose at least one friend');return;}if(id==='new'){S.goals.push(Object.assign({id:uid(),area:currentArea},fields));areaGoalForm=null;}else{var g=S.goals.find(function(x){return x.id===id;});if(g)Object.assign(g,fields);areaGoalEdit=null;}save();render();flash('Goal saved');return;}id=b.getAttribute('data-goaldone');if(id){var doneGoal=S.goals.find(function(g){return g.id===id;});if(doneGoal)completeGoal(doneGoal);}},true);

function completeGoal(g,whenTs){if(g.completed)return;var people=goalPeople(g),ts=Number.isFinite(whenTs)?whenTs:Date.now(),oneTime=!g.cadence;if(oneTime){g.completed=true;g.completedAt=ts;}var ty={scripture:'note',prayer:'note',date:'inperson',quality:'inperson',workout:'inperson',outdoors:'inperson'}[g.kind]||'inperson';logEvent(g.area,people[0]||null,ty,g.text,g.details||'',ts,g.id,null,{personIds:people,goalCompleted:oneTime});flash(oneTime?'Goal completed':'Goal tended');}
