"use strict";
/* A brief, time-ordered look at fixed commitments between enabled Focus windows. */
var FOCUS_DEFAULT_BLOCKS=['early','lunch','commute'];
var focusDialogBlock=null;
function focusBlocks(){var saved=S.settings&&S.settings.focusBlocks;var valid=Array.isArray(saved)?saved.filter(function(id){return dayBlocks().some(function(b){return b.id===id;});}):[];return valid.length?valid:FOCUS_DEFAULT_BLOCKS.slice();}
function focusNavButtonHTML(){return '<button type="button" class="focus-nav-button utility-primary-button" data-focusopen="auto" aria-label="Open Focus briefing"><span class="focus-nav-spark utility-nav-icon" aria-hidden="true">✦</span><span>Focus</span></button>';}
function focusSettingsHTML(){var selected=focusBlocks();return '<div class="card focus-settings"><div class="subhead">Focus</div><p class="settings-help">Focus is always available in the main navigation. Choose the sections that start a new briefing window; Focus shows the current window through the next selected section, or midnight.</p><div class="focus-settings-options">'+dayBlocks().map(function(block){return '<label><input type="checkbox" data-focusblock="'+block.id+'"'+(selected.indexOf(block.id)!==-1?' checked':'')+'><span>'+esc(block.name)+'</span></label>';}).join('')+'</div><p class="settings-help">Focus shows calendar plans in this window, rhythms and goals due today with a selected time of day, and up to two people below 75 who are not already in those plans.</p></div>';}
function focusCurrentBlock(now){now=now||new Date();var blocks=dayBlocks(),minute=now.getHours()*60+now.getMinutes(),selected=focusBlocks(),current=blocks.filter(function(b){return selected.indexOf(b.id)!==-1&&(+b.start.slice(0,2)*60+ +b.start.slice(3))<=minute;});return (current.length?current[current.length-1]:blocks.find(function(b){return selected.indexOf(b.id)!==-1;})).id;}
function focusWindow(blockId,now){now=now||new Date();var blocks=dayBlocks(),index=blocks.findIndex(function(b){return b.id===blockId;});if(index<0)return null;var start=new Date(now.getFullYear(),now.getMonth(),now.getDate(),+blocks[index].start.slice(0,2),+blocks[index].start.slice(3));var selected=focusBlocks(),next=blocks.slice(index+1).find(function(b){return selected.indexOf(b.id)!==-1;});var end=next?new Date(now.getFullYear(),now.getMonth(),now.getDate(),+next.start.slice(0,2),+next.start.slice(3)):new Date(now.getFullYear(),now.getMonth(),now.getDate()+1);return {block:blocks[index],start:Math.max(start.getTime(),now.getTime()),end:end.getTime(),next:next};}
function focusClock(ts){return new Date(ts).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'}).replace(':00','');}
function focusRhythmDueToday(r,date){return rhythmScheduledToday(r,date)&&scheduleDayMatches(r,date);}
function focusData(blockId,now){now=now||new Date();var range=focusWindow(blockId,now);if(!range)return null;var items=[],covered={};
 var calendar=window._tendCalendarEvents||[];if(!calendar.length){try{var cache=JSON.parse(localStorage.getItem('tend:cal2')||'null');calendar=cache&&Array.isArray(cache.events)?cache.events:[];}catch(e){}}
 calendar.forEach(function(ev){if(ev.allDay||!Number.isFinite(+ev.s)||+ev.s>=range.end||(+ev.e||+ev.s+3600000)<=range.start)return;var time=Math.max(+ev.s,range.start),title=ev.t||'Calendar event',category=ev.cal||'Calendar';S.people.forEach(function(p){if(title.toLowerCase().indexOf(p.name.toLowerCase())!==-1){covered[p.id]=true;if(S.areas[p.area])category=S.areas[p.area].name;}});items.push({type:'calendar',time:time,exact:true,title:title,category:category,subtitle:focusClock(+ev.s)+(ev.e?'–'+focusClock(+ev.e):'')});});
 var blocks=dayBlocks();function blockTime(id){var b=blocks.find(function(x){return x.id===id;});return b?new Date(now.getFullYear(),now.getMonth(),now.getDate(),+b.start.slice(0,2),+b.start.slice(3)).getTime():null;}
 S.people.forEach(function(person){(person.rhythms||[]).forEach(function(r){if(!r.tod||r.tod==='anytime'||!focusRhythmDueToday(r,now))return;var time=blockTime(r.tod);if(time===null||time>=range.end||(time<range.start&&r.tod!==dayBlockAt(now)))return;time=Math.max(time,range.start);covered[person.id]=true;items.push({type:'rhythm',time:time,blockLabel:TODS[r.tod]||r.tod,exact:false,title:r.text||'Rhythm',category:S.areas[person.area]?S.areas[person.area].name:'People',subtitle:rhythmFreqLabel(r),personId:person.id,rhythmId:r.id});});});
 S.goals.forEach(function(g){if(g.completed||!g.cadence||!g.tod||g.tod==='anytime'||goalHasRhythm(g)||!scheduleDayMatches(g,now))return;var days=goalLastDone(g);if(days===0||(days!==null&&days<goalInterval(g)))return;var time=blockTime(g.tod);if(time===null||time>=range.end||(time<range.start&&g.tod!==dayBlockAt(now)))return;time=Math.max(time,range.start);(Array.isArray(g.personIds)?g.personIds:[g.personId]).filter(Boolean).forEach(function(id){covered[id]=true;});items.push({type:'goal',time:time,blockLabel:TODS[g.tod]||g.tod,exact:false,title:g.text,category:S.areas[g.area]?S.areas[g.area].name:'Goal',subtitle:goalFrequency(g),personId:g.personId,goalId:g.id});});
 items.sort(function(a,b){return a.time-b.time||Number(b.exact)-Number(a.exact)||a.title.localeCompare(b.title);});
 var people=S.people.map(function(p){return {person:p,score:personScore(p),info:personConnInfo(p)};}).filter(function(x){return x.score<75&&!covered[x.person.id];}).sort(function(a,b){return a.score-b.score;}).slice(0,2);
 return {range:range,items:items,people:people};
}
function focusCategoryLabel(name){return name==='Health & Fitness'?'Fitness':name;}
function focusCategoryClass(name){var text=String(name).toLowerCase();if(text.indexOf('marriage')>=0)return 'marriage';if(text.indexOf('faith')>=0)return 'faith';if(text.indexOf('fitness')>=0||text.indexOf('health')>=0)return 'fitness';if(text.indexOf('parent')>=0)return 'parenting';if(text.indexOf('friend')>=0)return 'friendships';return 'calendar';}
function focusDialogHTML(blockId){var data=focusData(blockId);if(!data)return '';var block=data.range.block,heading=blockId==='commute'?'Tonight':block.name,until=data.range.next?'until '+data.range.next.name.toLowerCase():'through tonight';var out='<div class="focus-head"><div><div class="focus-eyebrow">Tend · Focus</div><h2 id="focusTitle">'+esc(heading)+'</h2><p>Just what’s fixed or due, '+esc(until)+'.</p></div><button type="button" class="iconbtn focus-close" data-focusclose aria-label="Close Focus">✕</button></div>';
 out+='<div class="focus-group"><div class="focus-group-head"><h3>Coming up</h3><span>'+data.items.length+' fixed plan'+(data.items.length===1?'':'s')+'</span></div>';
 if(!data.items.length)out+='<div class="focus-empty">No fixed plans left in this window.</div>';
 data.items.forEach(function(item){var label=item.exact?focusClock(item.time):item.blockLabel||'Scheduled',person=item.personId&&S.people.find(function(candidate){return candidate.id===item.personId;}),action=item.type==='rhythm'?'<button type="button" class="btn mini focus-action" data-tend-open="person-rhythm" data-person-id="'+esc(item.personId)+'" data-rhythm-id="'+esc(item.rhythmId)+'">Tend</button>':item.type==='goal'?'<button type="button" class="btn mini focus-action" data-tend-open="goal" data-goal-id="'+esc(item.goalId)+'">Tend</button>':'';out+='<div class="focus-item"><span class="focus-time">'+esc(label)+'</span><div class="focus-item-main"><strong>'+esc(item.title)+'</strong><small>'+esc(item.subtitle)+'</small></div>'+'<div class="focus-badges">'+(person?'<button type="button" class="focus-person-badge" data-focusperson="'+esc(person.id)+'" aria-label="Open '+esc(person.name)+'"><span class="focus-avatar">'+personAvatar(person,24)+'</span><span>'+esc(person.name)+'</span></button>':'')+'<span class="focus-kind '+focusCategoryClass(item.category)+'">'+esc(focusCategoryLabel(item.category))+'</span></div>'+action+'</div>';});
 out+='</div><div class="focus-group"><div class="focus-group-head"><h3>People to notice</h3><span>below 75</span></div>';
 if(!data.people.length)out+='<div class="focus-empty">No extra touchpoints need your attention.</div>';
 data.people.forEach(function(x){var p=x.person,days=x.info.days;out+='<button type="button" class="focus-person" data-focusperson="'+esc(p.id)+'"><span class="focus-avatar">'+personAvatar(p,34)+'</span><span class="focus-person-main"><strong>'+esc(p.name)+'</strong><small>'+(days===999?'No connection logged':days===0?'Connected today':'Last connected '+days+' days ago')+'</small></span><span class="focus-score '+scoreClass(x.score)+'">'+x.score+'</span></button>';});
 return out+'</div><div class="focus-footer">Flexible items stay on your dashboard.</div>';
}
function focusRefreshDialog(){var dialog=document.getElementById('focusDialog');if(dialog&&focusDialogBlock)dialog.innerHTML=focusDialogHTML(focusDialogBlock);}
function openFocus(blockId){if(!blockId||blockId==='auto')blockId=focusCurrentBlock(new Date());var previous=document.getElementById('focusDialog');if(previous)previous.remove();focusDialogBlock=blockId;var dialog=document.createElement('dialog');dialog.id='focusDialog';dialog.className='focus-dialog';dialog.setAttribute('aria-labelledby','focusTitle');dialog.innerHTML=focusDialogHTML(blockId);dialog.addEventListener('close',function(){dialog.remove();focusDialogBlock=null;});document.body.appendChild(dialog);dialog.showModal();}
document.addEventListener('click',function(e){var t=e.target,b;if(b=t.closest('[data-focusopen]')){openFocus(b.getAttribute('data-focusopen'));return;}if(b=t.closest('[data-focusclose]')){var dialog=document.getElementById('focusDialog');if(dialog)dialog.close();return;}if(b=t.closest('[data-focusperson]')){var pid=b.getAttribute('data-focusperson'),dialog=document.getElementById('focusDialog');if(dialog)dialog.close();openPersonTab(pid);return;}});
document.addEventListener('change',function(e){var t=e.target;if(!t.matches('[data-focusblock]'))return;S.settings=S.settings||{};var selected=Array.from(document.querySelectorAll('[data-focusblock]:checked')).map(function(c){return c.getAttribute('data-focusblock');});if(!selected.length){t.checked=true;flash('Keep at least one Focus time section');return;}S.settings.focusBlocks=selected;save();flash('Focus time sections saved');});
